#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: Service
metadata:
  name: {{ include "scaleph.fullname" . }}-ui
  labels:
    {{- include "scaleph-ui.labels" . | nindent 4 }}
  {{- if and (eq .Values.scalephui.service.type "LoadBalancer") .Values.scalephui.service.annotations }}
  annotations:
    {{- range $key, $value := .Values.scalephui.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.scalephui.service.type }}
  {{- if and (eq .Values.scalephui.service.type "ClusterIP") .Values.scalephui.service.clusterIP }}
  clusterIP: {{ .Values.scalephui.service.clusterIP }}
  {{- end }}
  ports:
    - port: 4200
      targetPort: scaleph-ui
      {{- if and (eq .Values.scalephui.service.type "NodePort") .Values.scalephui.service.nodePort }}
      nodePort: {{ .Values.scalephui.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: scaleph-ui
  {{- if .Values.scalephui.service.externalIPs }}
  externalIPs:
  {{- toYaml .Values.scalephui.service.externalIPs | nindent 4 }}
  {{- end }}
  {{- if and (eq .Values.scalephui.service.type "ExternalName") .Values.scalephui.service.externalName }}
  externalName: {{ .Values.scalephui.service.externalName }}
  {{- end }}
  {{- if and (eq .Values.scalephui.service.type "LoadBalancer") .Values.scalephui.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.scalephui.service.loadBalancerIP }}
  {{- end }}
  selector:
    {{- include "scaleph-ui.selectorLabels" . | nindent 4 }}
