version: '3'
services:
  docker-fe:
    image: "freeoneplus/apache-doris:1.1.0-perview2-fe"
    container_name: "doris-fe"
    tty: true
    hostname: "fe"
    restart: always
    ports:
      - 8030:8030
      - 9030:9030
    networks:
      doris_net:
        ipv4_address: 172.20.80.2
  docker-be:
    image: "freeoneplus/apache-doris:1.1.0-perview2-be"
    container_name: "doris-be"
    tty: true
    hostname: "fe"
    restart: always
    ports:
      - 8040:8040
      - 9050:9050
    networks:
      doris_net:
        ipv4_address: 172.20.80.3
  register:
    image: "freeoneplus/apache-doris:register"
    container_name: "doris-register"
    hostname: "register"
    privileged: true
    command: ["sh","-c","/root/register.sh"]
    depends_on:
      - docker-fe
      - docker-be
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      doris_net:
        ipv4_address: 172.20.80.4
networks:
  doris_net:
    ipam:
      config:
      - subnet: 172.20.80.0/16