name: CI

on:
  pull_request:
    paths-ignore: ['docs/**', '**/*.md', '**/*.drawio', '**/*.svg' ]
  push:
    paths-ignore: ['docs/**', '**/*.md', '**/*.drawio', '**/*.svg' ]
  schedule:
    - cron: '0 3 * * *' # automatic test while every day on 03:00 am
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        jdk: [ 8.0.322+6, 11, 17 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: adopt
          cache: maven
      - name: Build with Maven
        run: mvn -B -Dmaven.test.skip=true clean package --file pom.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
      
      
