name: Docker-Release

on:
  push:
    paths-ignore: ['docs/**', '**/*.md', '**/*.drawio', '**/*.svg' ]
    branches:
      - master

env:
  HUB: ghcr.io/flowerfine/scaleph

jobs:
  release:
    if: github.repository == 'flowerfine/scaleph'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8.0.322+6
          distribution: adopt
          cache: maven

      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.HUB }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push docker images
        run: |
          mvn -B clean deploy \
          -DskipTests \
          -Dmaven.javadoc.skip \
          -Dmaven.checkstyle.skip \
          -Dmaven.deploy.skip \
          -Ddocker.build.skip=false \
          -Ddocker.push.skip=false \
          -Ddocker.tag=${{ github.sha }} \
          -Ddocker.hub=${{ env.HUB }} \
          -Pdocker
