name: Docker-Build

on:
  push:
    paths-ignore: ['docs/**', '**/*.md', '**/*.drawio', '**/*.svg' ]
  pull_request:
    paths-ignore: [ 'docs/**', '**/*.md', '**/*.drawio', '**/*.svg' ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build docker images
        run: docker-compose -f tools/docker/build/scaleph/docker-compose.yml up -d
