name: Release

on:
  push:
    tags:
      - 'v*'

env:
  HUB: ghcr.io/flowerfine/scaleph

jobs:
  release:
    if: github.repository == 'flowerfine/scaleph'
    strategy:
      matrix:
        image: [ scaleph-api, scaleph-ui-react, scaleph-file-fetcher, mysql ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.HUB }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build scaleph-ui-react
        run: cd scaleph-ui-react && npm install && npm run build --prod
      - name: Build scaleph-file-fetcher
        run: mvn -B -U -T 4 clean package -Pdist -DskipTests -Dfast -am --projects scaleph-file-fetcher
      - name: Release image
        uses: docker/build-push-action@v4
        with:
          no-cache: false
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          file: tools/docker/build/${{ matrix.image }}/Dockerfile
          tags: |
            ${{ env.HUB }}/${{ matrix.image }}:${{ github.sha }},
            ${{ env.HUB }}/${{ matrix.image }}:${{ github.ref_name }}