name: Release

on:
  push:
    tags:
      - 'v*'

env:
  HUB: ghcr.io/flowerfine/scaleph

jobs:
  release:
    if: github.repository == 'flowerfine/scaleph'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.HUB }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Push scaleph-api image
        uses: docker/build-push-action@v4
        with:
          no-cache: true
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          file: tools/docker/build/scaleph-api/Dockerfile
          tags: |
            ${{ env.HUB }}/scaleph-api:${{ github.sha }},
            ${{ env.HUB }}/scaleph-api:${{ github.ref_name }}
      - name: Push scaleph-ui-react image
        uses: docker/build-push-action@v4
        with:
          no-cache: true
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          file: tools/docker/build/scaleph-ui-react/Dockerfile
          tags: |
            ${{ env.HUB }}/scaleph-ui-react:${{ github.sha }},
            ${{ env.HUB }}/scaleph-ui-react:${{ github.ref_name }}
      - name: Push mysql image
        uses: docker/build-push-action@v4
        with:
          no-cache: true
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          file: tools/docker/build/mysql/Dockerfile
          tags: |
            ${{ env.HUB }}/mysql:${{ github.sha }},
            ${{ env.HUB }}/mysql:${{ github.ref_name }}