name: sonarcloud

on:
  pull_request:
    paths-ignore: ['docs/**', '**/*.md', '**/*.drawio', '**/*.svg' ]
  push:
    paths-ignore: ['docs/**', '**/*.md', '**/*.drawio', '**/*.svg' ]
  schedule:
    - cron: '0 3 * * *' # automatic test while every day on 03:00 am
  workflow_dispatch:

jobs:
  sonarcloud-scan:
    if: github.repository == 'flowerfine/scaleph'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8.0.322+6
          distribution: adopt
          cache: maven

      - name: Run SonarCloud Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn -B verify sonar:sonar
          -Dmaven.test.skip=true
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=flowerfine
          -Dsonar.projectKey=flowerfine_scaleph