name: Web-IDE

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  web-ide:
    if: github.repository == 'flowerfine/scaleph'
    runs-on: ubuntu-latest
    steps:
      - name: echo env
        run: echo '${{ github.head_ref }}' & echo '${{ github.ref }}' & echo '${{ github.base_ref }}'

      - name: Web-IDE Pull Request Check
        uses: redhat-actions/try-in-web-ide@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          web_ide_instance: https://github.dev/flowerfine/scaleph/${{ github.head_ref }}
          comment_badge: https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white